# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: [push, pull_request]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_SUGGESTS_ONLY_: true

    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-tinytex@v1
      - run: |
          tlmgr --version
          tlmgr install ae  ## Needed by vignette
          tlmgr list --only-installed

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
        
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr

      - name: Test coverage
        ##  set 'CODECOV_TOKEN' in GitHub Secrets:
        ##    https://github.com/<org>/<repo>/settings/environments/
        
        run: |
          coverage <- covr::package_coverage()
          print(coverage)
          covr::codecov(coverage = coverage, token="${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}
